:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2015.4
:: Copyright (C) 2015 Xilinx Inc. All rights reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx/Vivado_HLS/2015.4/../../Vivado/2015.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z010clg400-1 ../UC3M_MISEA_thesis_ANN_2_1.zip
