// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern void ANN (
const int config[6],
const double WandB[4][35][36],
double uOut[4][35],
const double netIn[35],
int netOut[35]);
