// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _sigmoid_HH_
#define _sigmoid_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sigmoid_dadd_64ns_64ns_64_5_full_dsp.h"
#include "sigmoid_ddiv_64ns_64ns_64_31.h"
#include "sigmoid_dexp_64ns_64ns_64_18_full_dsp.h"
#include "sigmoid_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 5,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct sigmoid : public sc_module {
    // Port declarations 24
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<64> > ap_return;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;


    // Module declarations
    sigmoid(sc_module_name name);
    SC_HAS_PROCESS(sigmoid);

    ~sigmoid();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sigmoid_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* sigmoid_AXILiteS_s_axi_U;
    sigmoid_dadd_64ns_64ns_64_5_full_dsp<1,5,64,64,64>* sigmoid_dadd_64ns_64ns_64_5_full_dsp_U0;
    sigmoid_ddiv_64ns_64ns_64_31<1,31,64,64,64>* sigmoid_ddiv_64ns_64ns_64_31_U1;
    sigmoid_dexp_64ns_64ns_64_18_full_dsp<1,18,64,64,64>* sigmoid_dexp_64ns_64ns_64_18_full_dsp_U2;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_0;
    sc_signal< bool > ap_sig_bdd_19;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it5;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it6;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it7;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it8;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it9;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it10;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it11;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it12;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it13;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it14;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it15;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it16;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it17;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it18;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it19;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it20;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it21;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it22;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it23;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it24;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it25;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it26;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it27;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it28;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it29;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it30;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it31;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it32;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it33;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it34;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it35;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it36;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it37;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it38;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it39;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it40;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it41;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it42;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it43;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it44;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it45;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it46;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it47;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it48;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it49;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it50;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it51;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it52;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it53;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it54;
    sc_signal< sc_lv<64> > in_r;
    sc_signal< sc_logic > sigmoid_AXILiteS_s_axi_U_ap_dummy_ce;
    sc_signal< sc_lv<64> > in_read_reg_65;
    sc_signal< sc_lv<64> > grp_fu_46_p2;
    sc_signal< sc_lv<64> > tmp_1_reg_75;
    sc_signal< sc_lv<64> > grp_fu_36_p2;
    sc_signal< sc_lv<64> > tmp_2_reg_80;
    sc_signal< sc_lv<64> > grp_fu_46_p1;
    sc_signal< sc_lv<64> > tmp_to_int_fu_51_p1;
    sc_signal< sc_lv<64> > tmp_neg_fu_54_p2;
    sc_signal< sc_logic > grp_fu_36_ce;
    sc_signal< sc_lv<64> > grp_fu_41_p2;
    sc_signal< sc_logic > grp_fu_41_ce;
    sc_signal< sc_logic > grp_fu_46_ce;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< sc_logic > ap_sig_pprstidle_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_pp0_stg0_fsm_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<64> ap_const_lv64_3FF0000000000000;
    static const sc_lv<64> ap_const_lv64_8000000000000000;
    static const sc_lv<64> ap_const_lv64_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_reg_ppiten_pp0_it0();
    void thread_ap_return();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_bdd_19();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_0();
    void thread_ap_sig_pprstidle_pp0();
    void thread_grp_fu_36_ce();
    void thread_grp_fu_41_ce();
    void thread_grp_fu_46_ce();
    void thread_grp_fu_46_p1();
    void thread_sigmoid_AXILiteS_s_axi_U_ap_dummy_ce();
    void thread_tmp_neg_fu_54_p2();
    void thread_tmp_to_int_fu_51_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
