webtalk_init -webtalk_dir E:\\TFM\\ANN_project\\ANN_project.sdk_SWandHW_standalone_v2\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 2 05:11:03 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "hphhmroosa02vv550dm2mlvf6q" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1472773650685" -context "sdk\\\\hardware/1472773650685"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1472773650685"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1472773650685"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4.2" -context "sdk\\\\hardware/1472773650685"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1472773650685"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1472773650685"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1472773650685"
webtalk_add_data -client sdk -key uid -value "1472773671012" -context "sdk\\\\bsp/1472773671012"
webtalk_add_data -client sdk -key hwid -value "1472773650685" -context "sdk\\\\bsp/1472773671012"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1472773671012"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1472773671012"
webtalk_add_data -client sdk -key uid -value "1472773778655" -context "sdk\\\\application/1472773778655"
webtalk_add_data -client sdk -key hwid -value "1472773650685" -context "sdk\\\\application/1472773778655"
webtalk_add_data -client sdk -key bspid -value "1472773671012" -context "sdk\\\\application/1472773778655"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1472773778655"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1472773778655"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1472773778655"
webtalk_transmit -clientid 1575855573 -regid "" -xml E:\\TFM\\ANN_project\\ANN_project.sdk_SWandHW_standalone_v2\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\TFM\\ANN_project\\ANN_project.sdk_SWandHW_standalone_v2\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\TFM\\ANN_project\\ANN_project.sdk_SWandHW_standalone_v2\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
