# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/TFM/ANN_project/ANN_project.cache/wt [current_project]
set_property parent.project_path E:/TFM/ANN_project/ANN_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files E:/TFM/ANN_project/ANN_project.srcs/sources_1/bd/design_SW_standalone/design_SW_standalone.bd
set_property used_in_implementation false [get_files -all e:/TFM/ANN_project/ANN_project.srcs/sources_1/bd/design_SW_standalone/ip/design_SW_standalone_processing_system7_0_0/design_SW_standalone_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all E:/TFM/ANN_project/ANN_project.srcs/sources_1/bd/design_SW_standalone/design_SW_standalone_ooc.xdc]
set_property is_locked true [get_files E:/TFM/ANN_project/ANN_project.srcs/sources_1/bd/design_SW_standalone/design_SW_standalone.bd]

read_vhdl -library xil_defaultlib E:/TFM/ANN_project/ANN_project.srcs/sources_1/bd/design_SW_standalone/hdl/design_SW_standalone_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_SW_standalone_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef design_SW_standalone_wrapper.dcp
catch { report_utilization -file design_SW_standalone_wrapper_utilization_synth.rpt -pb design_SW_standalone_wrapper_utilization_synth.pb }
