# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ANN_SW_design/ANN_SW_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ANN_SW_design || ORIG_REF_NAME==ANN_SW_design}]

# IP: bd/ANN_SW_design/ip/ANN_SW_design_axi_gpio_0_0/ANN_SW_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ANN_SW_design_axi_gpio_0_0 || ORIG_REF_NAME==ANN_SW_design_axi_gpio_0_0}]

# IP: bd/ANN_SW_design/ip/ANN_SW_design_processing_system7_0_1/ANN_SW_design_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ANN_SW_design_processing_system7_0_1 || ORIG_REF_NAME==ANN_SW_design_processing_system7_0_1}]

# IP: bd/ANN_SW_design/ip/ANN_SW_design_processing_system7_0_axi_periph_1/ANN_SW_design_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ANN_SW_design_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==ANN_SW_design_processing_system7_0_axi_periph_1}]

# IP: bd/ANN_SW_design/ip/ANN_SW_design_rst_processing_system7_0_100M_1/ANN_SW_design_rst_processing_system7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ANN_SW_design_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==ANN_SW_design_rst_processing_system7_0_100M_1}]

# IP: bd/ANN_SW_design/ip/ANN_SW_design_auto_pc_1/ANN_SW_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ANN_SW_design_auto_pc_1 || ORIG_REF_NAME==ANN_SW_design_auto_pc_1}]

# XDC: bd/ANN_SW_design/ip/ANN_SW_design_axi_gpio_0_0/ANN_SW_design_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ANN_SW_design_axi_gpio_0_0 || ORIG_REF_NAME==ANN_SW_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ANN_SW_design/ip/ANN_SW_design_axi_gpio_0_0/ANN_SW_design_axi_gpio_0_0_ooc.xdc

# XDC: bd/ANN_SW_design/ip/ANN_SW_design_axi_gpio_0_0/ANN_SW_design_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ANN_SW_design_axi_gpio_0_0 || ORIG_REF_NAME==ANN_SW_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ANN_SW_design/ip/ANN_SW_design_processing_system7_0_1/ANN_SW_design_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ANN_SW_design_processing_system7_0_1 || ORIG_REF_NAME==ANN_SW_design_processing_system7_0_1}] {/inst }]/inst ]]

# XDC: bd/ANN_SW_design/ip/ANN_SW_design_rst_processing_system7_0_100M_1/ANN_SW_design_rst_processing_system7_0_100M_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ANN_SW_design_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==ANN_SW_design_rst_processing_system7_0_100M_1}]

# XDC: bd/ANN_SW_design/ip/ANN_SW_design_rst_processing_system7_0_100M_1/ANN_SW_design_rst_processing_system7_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ANN_SW_design_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==ANN_SW_design_rst_processing_system7_0_100M_1}]

# XDC: bd/ANN_SW_design/ip/ANN_SW_design_rst_processing_system7_0_100M_1/ANN_SW_design_rst_processing_system7_0_100M_1_ooc.xdc

# XDC: bd/ANN_SW_design/ip/ANN_SW_design_auto_pc_1/ANN_SW_design_auto_pc_1_ooc.xdc

# XDC: bd/ANN_SW_design/ANN_SW_design_ooc.xdc
