// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xann.h"

extern XAnn_Config XAnn_ConfigTable[];

XAnn_Config *XAnn_LookupConfig(u16 DeviceId) {
	XAnn_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XANN_NUM_INSTANCES; Index++) {
		if (XAnn_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XAnn_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XAnn_Initialize(XAnn *InstancePtr, u16 DeviceId) {
	XAnn_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XAnn_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XAnn_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

