webtalk_init -webtalk_dir E:\\TFM\\ANN_project\\ANN_project.sdk_SW_standalone\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Aug 27 17:33:51 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "puka33lbbiihuj3c2cr0f1o12g" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_22" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1472267540690" -context "sdk\\\\application/1472267540690"
webtalk_add_data -client sdk -key hwid -value "1472255855727" -context "sdk\\\\application/1472267540690"
webtalk_add_data -client sdk -key bspid -value "1472258310928" -context "sdk\\\\application/1472267540690"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1472267540690"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1472267540690"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1472267540690"
webtalk_transmit -clientid 169663988 -regid "" -xml E:\\TFM\\ANN_project\\ANN_project.sdk_SW_standalone\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\TFM\\ANN_project\\ANN_project.sdk_SW_standalone\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\TFM\\ANN_project\\ANN_project.sdk_SW_standalone\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
