webtalk_init -webtalk_dir E:\\TFM\\ANN_project\\ANN_project.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 23 02:21:25 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "r6m4e4k6tp2jj13tjibgab47s9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_18" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1466640818155" -context "sdk\\\\hardware/1466640818155"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1466640818155"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1466640818155"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4.2" -context "sdk\\\\hardware/1466640818155"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1466640818155"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1466640818155"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1466640818155"
webtalk_add_data -client sdk -key uid -value "1466640958995" -context "sdk\\\\hardware/1466640958995"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1466640958995"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1466640958995"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4.2" -context "sdk\\\\hardware/1466640958995"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1466640958995"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1466640958995"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1466640958995"
webtalk_add_data -client sdk -key uid -value "1466640976567" -context "sdk\\\\bsp/1466640976567"
webtalk_add_data -client sdk -key hwid -value "1466640958995" -context "sdk\\\\bsp/1466640976567"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1466640976567"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1466640976567"
webtalk_add_data -client sdk -key uid -value "1466641168089" -context "sdk\\\\bsp/1466641168089"
webtalk_add_data -client sdk -key hwid -value "1466640958995" -context "sdk\\\\bsp/1466641168089"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1466641168089"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1466641168089"
webtalk_transmit -clientid 3410969435 -regid "" -xml E:\\TFM\\ANN_project\\ANN_project.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\TFM\\ANN_project\\ANN_project.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\TFM\\ANN_project\\ANN_project.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
