webtalk_init -webtalk_dir E:\\ANN_project\\ANN_project.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 13 00:13:28 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "uvrqsni4su8hudoj78vgel97pn" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1465690614808" -context "sdk\\\\application/1465690614808"
webtalk_add_data -client sdk -key hwid -value "1463092759185" -context "sdk\\\\application/1465690614808"
webtalk_add_data -client sdk -key bspid -value "1463092795208" -context "sdk\\\\application/1465690614808"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1465690614808"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1465690614808"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1465690614808"
webtalk_add_data -client sdk -key uid -value "1465690976754" -context "sdk\\\\application/1465690976754"
webtalk_add_data -client sdk -key hwid -value "1463092759185" -context "sdk\\\\application/1465690976754"
webtalk_add_data -client sdk -key bspid -value "1463092795208" -context "sdk\\\\application/1465690976754"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1465690976754"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1465690976754"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1465690976754"
webtalk_transmit -clientid 1710961947 -regid "" -xml E:\\ANN_project\\ANN_project.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\ANN_project\\ANN_project.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\ANN_project\\ANN_project.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
